export const savedFieldTitles = [
  'STT/Mã bệnh nhân',
  'Địa điểm khám',
  'Ngày khám',
  'Họ và Tên',
  'Năm sinh',
  'Tuổi',
  'Số điện thoại',
  'Chiều cao',
  'Cân nặng',
  'Dân tộc',
  'Phường/xã',
  'Tỉnh/TP',
  'Đơn vị công tác',
  'Chi tiết',
  'Trình độ',
  'PARA',
  'Tuổi QHTD đầu tiên',
  'Đời sống tình cảm',
  'Biện pháp tránh thai',
  'Tiêm vắc xin HPV?',
  'Loại vắc xin đã tiêm',
  'Số mũi',
  'Đã tầm soát UTCTC?',
  'Phương pháp đã làm',
  'Kết quả',
  'Năm tầm soát',
  'Bệnh phụ khoa',
  'Bệnh nền',
  'Hút thuốc lá',
  'Bia rượu',
  'Tình trạng HIV',
  'Thuốc ức chế MD',
  'Tập thể dục',
  'Bơi lội',
  'GĐ mắc UT CTC?',
  'Triệu chứng hiện tại',
  'Kết quả AI',
  'Nhận xét của Bác Sĩ',
  'Hướng xử trí',
]

export const savedFieldNameByTitle: Record<string, string> = {
  'STT/Mã bệnh nhân': 'patientCode',
  'Địa điểm khám': 'clinicLocation',
  'Ngày khám': 'examDate',
  'Họ và Tên': 'fullName',
  'Năm sinh': 'birthYear',
  Tuổi: 'age',
  'Số điện thoại': 'phoneNumber',
  'Chiều cao': 'height',
  'Cân nặng': 'weight',
  'Dân tộc': 'ethnicity',
  'Phường/xã': 'ward',
  'Tỉnh/TP': 'province',
  'Đơn vị công tác': 'workplace',
  'Chi tiết': 'details',
  'Trình độ': 'education',
  PARA: 'para',
  'Tuổi QHTD đầu tiên': 'firstSexAge',
  'Đời sống tình cảm': 'relationshipStatus',
  'Biện pháp tránh thai': 'contraception',
  'Tiêm vắc xin HPV?': 'hpvVaccinated',
  'Loại vắc xin đã tiêm': 'hpvVaccineType',
  'Số mũi': 'hpvDoseCount',
  'Đã tầm soát UTCTC?': 'cervicalCancerScreened',
  'Phương pháp đã làm': 'screeningMethod',
  'Kết quả': 'screeningResult',
  'Năm tầm soát': 'screeningYear',
  'Bệnh phụ khoa': 'gynecologicalDisease',
  'Bệnh nền': 'underlyingDisease',
  'Hút thuốc lá': 'smoking',
  'Bia rượu': 'alcohol',
  'Tình trạng HIV': 'hivStatus',
  'Thuốc ức chế MD': 'immunosuppressant',
  'Tập thể dục': 'exercise',
  'Bơi lội': 'swimming',
  'GĐ mắc UT CTC?': 'familyCervicalCancer',
  'Triệu chứng hiện tại': 'currentSymptoms',
  'Kết quả AI': 'aiResult',
  'Nhận xét của Bác Sĩ': 'doctorComment',
  'Hướng xử trí': 'treatmentPlan',
}
